### ISSUE TITLE
Yoda lift shouldn't re-lift dependencies that are already running

### ISSUE THREAD

**Issue by jklewa** [kcmerrill/yoda#17] opened 2015-05-21 22:53 UTC

**Comment by kcmerrill** [comment] 2015-10-12 06:12
Hmmmm, controversial :)

Maybe we can add a config flag, but ideally, yoda should relift everything all the time so that way we don't run into any weird issues like, did you pull xyz dependency too? Yes, it takes a little longer, but ... I think this one done by design this way. Closing for now, but if we can think of another reason to do this then we can chat about it.

**Closed as completed by kcmerrill** 2015-10-12 06:12 UTC
